server:
  port: 8071

encrypt:
  key: 0192c5f0-dc9c-7b2b-8ec7-e30b7947a9da

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: "config-server"
  profiles:
    #    active: native
    active: git
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: "https://github.com/Moraveis/udemy-microservices-configs.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #        native:
  #          search-locations: "classpath:/config"
  #          search-locations: "file:///path//to//folder"
  rabbitmq:
    host: "localhost"
    post: 5672
    username: "guest"
    password: "guest"