server:
  port: 8071

encrypt:
  key: 0192c5f0-dc9c-7b2b-8ec7-e30b7947a9da

spring:
  application:
    name: config-server
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Moraveis/udemy-microservices-configs.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///path//to//folder"
